"""
BIS Specialized Agents Catalog.
16 Domain-Specific AI Compliance & Standards Agents for the BIS Sahayak Marketplace.
"""

AGENTS_CATALOG = [
    {
        "id": "agent-footwear",
        "name": "Footwear & PPE Conformance Specialist",
        "name_hi": "जूते व पीपीई मानक विशेषज्ञ",
        "category": "safety",
        "category_label": "Safety & PPE",
        "icon": "TXD",
        "badge": "Mandatory QCO 2020",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 15298 (Part 2)", "IS 10702", "IS 15844"],
        "description": "Specialized in industrial safety footwear, steel toe caps, anti-slip soles, and Footwear Quality Control Orders.",
        "description_hi": "औद्योगिक सुरक्षा जूते, स्टील टो कैप, एंटी-स्लिप सोल और फुटवियर गुणवत्ता नियंत्रण आदेश में विशेषज्ञ।",
        "key_tests": "200J Toe-Cap Impact, Sole Adhesion, Slip Resistance, Electrical Resistance",
        "default_question": "Which safety footwear is mandatory under Footwear QCO and what are the MSME fee concessions?",
        "system_role": "You are the Senior Technical Assessor for Footwear & Leather Products at the Bureau of Indian Standards (IS 15298, IS 10702, Footwear QCO). Provide deep technical guidance on industrial safety footwear, testing parameters, and certification exemptions (such as casual Hawai chappals)."
    },
    {
        "id": "agent-helmets",
        "name": "Automotive & Two-Wheeler Safety Inspector",
        "name_hi": "हेलमेट व ऑटोमोटिव सुरक्षा निरीक्षक",
        "category": "safety",
        "category_label": "Safety & PPE",
        "icon": "TED",
        "badge": "Mandatory Two-Wheeler QCO",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 4151", "IS 15636", "IS 14812"],
        "description": "Expert in motorcycle protective helmets, drop impact attenuation, chin strap retention, and mandatory ISI marking.",
        "description_hi": "मोटरसाइकिल सुरक्षा हेलमेट, शॉक अवशोषण, चिन-स्ट्रैप मजबूती और अनिवार्य आईएसआई मार्किंग में विशेषज्ञ।",
        "key_tests": "Drop Impact Attenuation, Retention System Dynamic Test, Visor Optical Purity",
        "default_question": "What standard applies to motorcycle helmets and what are the mandatory testing parameters under IS 4151?",
        "system_role": "You are the Bureau of Indian Standards Lead Conformity Officer for Automotive Two-Wheeler Safety and Motorcycle Helmets (IS 4151:2015). Focus on impact attenuation, mandatory ISI mark enforcement, MoRTH gazette notifications, and pneumatic tyre standards."
    },
    {
        "id": "agent-gold",
        "name": "Gold Jewellery & 6-Digit HUID Officer",
        "name_hi": "स्वर्ण आभूषण व HUID हॉलमार्किंग अधिकारी",
        "category": "hallmarking",
        "category_label": "Precious Metals",
        "icon": "HMD",
        "badge": "Mandatory Hallmarking",
        "scheme": "Scheme-IV (Hallmarking)",
        "standards": ["IS 1417:2016", "IS 2790", "IS 15820"],
        "description": "Authoritative guidance on 6-digit alphanumeric HUID, 14K/18K/20K/22K/24K purity grades, and AHC assaying procedures.",
        "description_hi": "6-अंकों के HUID, 14K/18K/20K/22K/24K शुद्धता ग्रेड और परख एवं हॉलमार्किंग केंद्रों (AHC) के नियमों में विशेषज्ञ।",
        "key_tests": "Fire Assay / Cupellation, X-Ray Fluorescence (XRF), 6-Digit HUID Laser Inscription",
        "default_question": "How do consumers verify a 6-digit HUID on gold jewellery using the BIS Care App?",
        "system_role": "You are the Director of Hallmarking at the Bureau of Indian Standards (IS 1417). Specialize in the 3 mandatory hallmark signs (BIS Triangle Crest, Purity in Carat/Fineness, and 6-digit HUID), Assaying & Hallmarking Centres (AHC), and consumer verification."
    },
    {
        "id": "agent-silver",
        "name": "Silver Jewellery & Artefacts Specialist",
        "name_hi": "चांदी आभूषण व कलाकृति विशेषज्ञ",
        "category": "hallmarking",
        "category_label": "Precious Metals",
        "icon": "HMD",
        "badge": "Silver Hallmarking Scheme",
        "scheme": "Scheme-IV (Hallmarking)",
        "standards": ["IS 2112:2014"],
        "description": "Expert in silver purity grades (999, 970, 925, 900, 835, 800), hallmarking procedures, and authenticity testing.",
        "description_hi": "चांदी के शुद्धता ग्रेड (999, 970, 925, 900, 835, 800) और हॉलमार्किंग प्रक्रिया में विशेषज्ञ।",
        "key_tests": "Potentiometric Titration, XRF Spectrometry, Fineness Verification",
        "default_question": "What purity grades are officially recognized for silver jewellery under IS 2112:2014?",
        "system_role": "You are the Senior Assayer for Silver Jewellery and Artefacts at the Bureau of Indian Standards (IS 2112:2014). Provide precise details on recognized silver purity grades, hallmarking symbols, and testing protocols."
    },
    {
        "id": "agent-crs-it",
        "name": "IT, Electronics & CRS Specialist",
        "name_hi": "आईटी व इलेक्ट्रॉनिक्स CRS विशेषज्ञ",
        "category": "electronics",
        "category_label": "Electronics & IT",
        "icon": "LITD",
        "badge": "Compulsory Registration (MeitY)",
        "scheme": "Scheme-II (CRS Registration)",
        "standards": ["IS 13252 (Part 1)", "IS 16046 (Part 2)", "IS 616"],
        "description": "Specialist in MeitY Compulsory Registration Scheme (CRS), mobile phones, laptops, lithium-ion battery safety, and R-numbers.",
        "description_hi": "MeitY अनिवार्य पंजीकरण योजना (CRS), मोबाइल फोन, लैपटॉप, लिथियम-आयन बैटरी सुरक्षा और R-नंबर में विशेषज्ञ।",
        "key_tests": "Electrical Safety, Temperature Rise, Overcharge & Short Circuit, Mechanical Shock",
        "default_question": "What is the difference between CRS R-number and ISI Mark for electronic goods under IS 13252?",
        "system_role": "You are the Head of Compulsory Registration Scheme (CRS / Scheme-II) at BIS for Electronics and IT Goods (IS 13252, IS 16046). Explain the self-declaration of conformity, NABL lab test reports, R-number portal registration, and differences from Scheme-I."
    },
    {
        "id": "agent-water",
        "name": "Packaged Water & Food Safety Auditor",
        "name_hi": "पेयजल व खाद्य सुरक्षा लेखापरीक्षक",
        "category": "food",
        "category_label": "Food & Water",
        "icon": "FAD",
        "badge": "Mandatory ISI + FSSAI Dual",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 14543", "IS 13428", "IS 10500"],
        "description": "Advising on Packaged Drinking Water, Natural Mineral Water, Drinking Water specifications, and in-house microbiological lab setups.",
        "description_hi": "पैकेज्ड ड्रिंक वॉटर, प्राकृतिक खनिज जल, पीने के पानी के मानकों और प्रयोगशाला परीक्षणों में विशेषज्ञ।",
        "key_tests": "Microbiological Purity (E. coli, Coliform, Pseudomonas), Total Dissolved Solids, Heavy Metals (Lead, Arsenic)",
        "default_question": "What in-house testing laboratory and hygienic conditions are mandatory under IS 14543 for packaged water?",
        "system_role": "You are the Lead Auditor for Food & Water Certification at the Bureau of Indian Standards (IS 14543, IS 13428, IS 10500). Detail water purification stages, mandatory in-house microbiological laboratory testing, and the dual FSSAI-BIS licensing framework."
    },
    {
        "id": "agent-steel",
        "name": "TMT Steel & Structural Conformance Agent",
        "name_hi": "TMT स्टील व सरिया गुणवत्ता विशेषज्ञ",
        "category": "industrial",
        "category_label": "Heavy & Construction",
        "icon": "MTD",
        "badge": "Steel Quality Control Order",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 1786:2008", "IS 2062", "IS 2830"],
        "description": "Expert in High Strength Deformed Steel Bars (Fe 415, Fe 500, Fe 500D, Fe 550), bend tests, and mandatory Steel QCO compliance.",
        "description_hi": "उच्च शक्ति विरूपित स्टील बार (Fe 500D सरिया), बेंड टेस्ट और इस्पात गुणवत्ता नियंत्रण आदेश के विशेषज्ञ।",
        "key_tests": "Tensile Strength, 0.2% Proof Stress, Elongation Percentage, Bend and Rebend Test",
        "default_question": "What is the mandatory standard for TMT sariya in India and why is Fe 500D preferred for earthquake zones?",
        "system_role": "You are the Chief Technical Inspector for Metallurgical and Steel Standards at BIS (IS 1786). Detail rebar grades (Fe 500, Fe 500D, Fe 550D), chemical composition limits (Carbon, Sulphur, Phosphorus), and the Ministry of Steel QCO."
    },
    {
        "id": "agent-cement",
        "name": "Portland Cement & Building Materials Specialist",
        "name_hi": "सीमेंट व भवन निर्माण सामग्री विशेषज्ञ",
        "category": "industrial",
        "category_label": "Heavy & Construction",
        "icon": "CED",
        "badge": "Cement Quality Control Order",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 1489 (Part 1)", "IS 269", "IS 456", "IS 303"],
        "description": "Specialized in Portland Pozzolana Cement (PPC), Ordinary Portland Cement (OPC 43/53), Plain & Reinforced Concrete, and Plywood.",
        "description_hi": "पोर्टलैंड पॉज़ोलाना सीमेंट (PPC), ओपीसी सीमेंट, कंक्रीट और प्लाईवुड मानकों में विशेषज्ञ।",
        "key_tests": "Compressive Strength (3, 7, 28 days), Setting Time (Initial/Final), Soundness (Le Chatelier/Autoclave)",
        "default_question": "What are the compressive strength requirements and setting times for PPC under IS 1489 (Part 1)?",
        "system_role": "You are the Senior Materials Engineer for Civil Engineering and Construction Standards at BIS (IS 1489, IS 269, IS 456, IS 303). Detail cement chemical fineness, compressive strength benchmarks, and building code compliance."
    },
    {
        "id": "agent-toys",
        "name": "Toys & Child Safety Conformance Agent",
        "name_hi": "खिलौने व बाल सुरक्षा मानक विशेषज्ञ",
        "category": "consumer",
        "category_label": "Consumer & Home",
        "icon": "PCD",
        "badge": "Toys Safety QCO 2020",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 9873 (Part 1-9)", "IS 15644"],
        "description": "Dedicated to the Toys (Quality Control) Order, mechanical/physical safety, non-toxic heavy metal migration, and electric toy safety.",
        "description_hi": "खिलौना (गुणवत्ता नियंत्रण) आदेश, यांत्रिक सुरक्षा, गैर-विषैले रंग और इलेक्ट्रिक खिलौनों के मानकों में विशेषज्ञ।",
        "key_tests": "Small Parts Choking Hazard, Sharp Edge & Point, Heavy Element Migration (Lead, Cadmium), Flammability",
        "default_question": "What are the mandatory testing requirements under Toys QCO 2020 before selling toys in India?",
        "system_role": "You are the Child Safety and Toys Certification Lead at the Bureau of Indian Standards (IS 9873, IS 15644). Enforce the zero-tolerance policy against toxic chemicals, sharp edges, and small parts choking hazards under the DPIIT Toys QCO."
    },
    {
        "id": "agent-appliances",
        "name": "Home Appliances & Electrical Safety Agent",
        "name_hi": "घरेलू विद्युत उपकरण सुरक्षा विशेषज्ञ",
        "category": "consumer",
        "category_label": "Consumer & Home",
        "icon": "ETD",
        "badge": "Electrical Appliances QCO",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 302 (Part 2)", "IS 374", "IS 2082", "IS 2347"],
        "description": "Specialized in electrical safety for electric irons, food mixers/grinders, ceiling fans, geysers, and domestic pressure cookers.",
        "description_hi": "इलेक्ट्रिक आयरन, मिक्सर/ग्राइंडर, सीलिंग फैन, गीजर और प्रेशर कुकर की सुरक्षा के विशेषज्ञ।",
        "key_tests": "High Voltage Dielectric Breakdown, Earth Continuity, Insulation Resistance, Overheating Protection",
        "default_question": "Which Indian Standard applies to domestic electric food mixers and grinders under IS 302-2-14?",
        "system_role": "You are the Electrical and Household Appliances Certification Specialist at BIS (IS 302 Part 2, IS 374, IS 2082, IS 2347). Explain consumer safety, leakage currents, earthing requirements, and mandatory quality directives."
    },
    {
        "id": "agent-gas-lpg",
        "name": "LPG Cylinders & Gas Appliances Inspector",
        "name_hi": "एलपीजी सिलेंडर व गैस उपकरण निरीक्षक",
        "category": "safety",
        "category_label": "Safety & PPE",
        "icon": "MED",
        "badge": "PESO & BIS Mandatory",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 3196 (Part 1-3)", "IS 4246"],
        "description": "Expert in welded low carbon steel LPG cylinders, gas stoves, burst pressure testing, and PESO explosive regulatory norms.",
        "description_hi": "एलपीजी गैस सिलेंडर, घरेलू गैस चूल्हा, हाइड्रोस्टैटिक प्रेशर और सुरक्षा मानकों में विशेषज्ञ।",
        "key_tests": "Hydrostatic Stretch Test, Pneumatic Leakage Check, Burst Pressure Verification, Thermal Efficiency",
        "default_question": "What hydrostatic pressure testing is mandatory for domestic LPG cylinders under IS 3196?",
        "system_role": "You are the Chief Gas Safety and Pressure Vessel Inspector for BIS (IS 3196, IS 4246). Detail safety procedures for welded steel gas cylinders, hydrostatic pressure tests (2.5 MPa), burst ratios, and domestic gas stove thermal efficiency."
    },
    {
        "id": "agent-fire-safety",
        "name": "Fire Fighting & Extinguishers Safety Auditor",
        "name_hi": "अग्निशमन यंत्र व अग्नि सुरक्षा लेखापरीक्षक",
        "category": "safety",
        "category_label": "Safety & PPE",
        "icon": "CED",
        "badge": "Fire Safety Mandatory",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 15683:2018", "IS 2190"],
        "description": "Authoritative guidance on portable fire extinguishers (ABC dry powder, CO2, water, foam), rating classes, and maintenance norms.",
        "description_hi": "पोर्टेबल अग्निशामक यंत्र (ABC ड्राई पाउडर, CO2, फोम) और अग्नि सुरक्षा रखरखाव में विशेषज्ञ।",
        "key_tests": "Hydrostatic Pressure Test, Fire Rating Performance (Class A/B/C/F), Discharge Duration & Range",
        "default_question": "What are the fire rating benchmarks and pressure limits for portable extinguishers under IS 15683?",
        "system_role": "You are the Technical Director for Fire Fighting Equipment and Extinguishers at BIS (IS 15683:2018, IS 2190). Provide rigorous technical explanations of extinguishing media, discharge mechanisms, and periodic hydrostatic stretch inspections."
    },
    {
        "id": "agent-solar",
        "name": "Solar PV & Renewable Energy Evaluator",
        "name_hi": "सौर पैनल व नवीकरणीय ऊर्जा विश्लेषक",
        "category": "industrial",
        "category_label": "Heavy & Construction",
        "icon": "ETD",
        "badge": "MNRE / CRS Order",
        "scheme": "Scheme-II (CRS Registration)",
        "standards": ["IS 14286", "IS/IEC 61730"],
        "description": "Guiding manufacturers through MNRE quality orders, crystalline silicon terrestrial PV modules, and solar inverter CRS registration.",
        "description_hi": "सौर पीवी मॉड्यूल (सोलर पैनल), इन्वर्टर और एमएनआरई गुणवत्ता नियंत्रण आदेश में विशेषज्ञ।",
        "key_tests": "Thermal Cycling Test, Damp Heat Endurance, Hail Impact Resistance, Wet Leakage Current",
        "default_question": "What testing is required for solar PV modules under IS 14286 and MNRE guidelines?",
        "system_role": "You are the Renewable Energy Conformance Officer at BIS for Solar Photovoltaic Modules and Systems (IS 14286, IS/IEC 61730). Explain compliance protocols for solar arrays, MNRE ALMM listing, and durability under extreme Indian climate conditions."
    },
    {
        "id": "agent-medical-ppe",
        "name": "Medical Devices & Health PPE Specialist",
        "name_hi": "चिकित्सा उपकरण व मास्क सुरक्षा विशेषज्ञ",
        "category": "consumer",
        "category_label": "Consumer & Home",
        "icon": "MHD",
        "badge": "CDSCO / BIS Standards",
        "scheme": "Scheme-I / Voluntary",
        "standards": ["IS 16289", "IS 3055 (Part 1-2)", "IS 9400"],
        "description": "Expert in surgical face masks, particulate respirators (N95 equivalent), clinical thermometers, and medical diagnostic equipment.",
        "description_hi": "सर्जिकल फेस मास्क, मेडिकल रेस्पिरेटर, क्लिनिकल थर्मामीटर और स्वास्थ्य उपकरणों में विशेषज्ञ।",
        "key_tests": "Bacterial Filtration Efficiency (BFE > 98%), Differential Pressure / Breathability, Splash Resistance",
        "default_question": "What are the Bacterial Filtration Efficiency (BFE) criteria for surgical masks under IS 16289?",
        "system_role": "You are the Medical Devices and Healthcare Standards Officer at the Bureau of Indian Standards (IS 16289, IS 3055). Focus on filtration efficiency, biological biocompatibility, fluid resistance, and thermometer accuracy."
    },
    {
        "id": "agent-cables",
        "name": "Cables, Wires & Electrical Conformance Officer",
        "name_hi": "केबल, तार व प्लग-सॉकेट मानक अधिकारी",
        "category": "electronics",
        "category_label": "Electronics & IT",
        "icon": "ETD",
        "badge": "Mandatory Electrical QCO",
        "scheme": "Scheme-I (ISI Mark)",
        "standards": ["IS 694", "IS 1293", "IS 7098"],
        "description": "Specialized in PVC insulated electrical cables up to 1100V, plugs & socket-outlets, flame retardance, and conductor resistance.",
        "description_hi": "पीवीसी इंसुलेटेड बिजली के तार (1100V), प्लग, सॉकेट और अग्निरोधक केबल मानकों में विशेषज्ञ।",
        "key_tests": "Conductor Resistance, Spark Test, Tensile Strength of Insulation, Oxygen Index / Flammability",
        "default_question": "What are the safety and conductor resistance limits for house wiring cables under IS 694?",
        "system_role": "You are the Electrical Engineering Division Head for Power Cables and Wiring Accessories at BIS (IS 694, IS 1293). Provide strict directives on pure electrolytic copper conductors, insulation breakdown, and plug pin dimensional tolerances."
    },
    {
        "id": "agent-care-msme",
        "name": "MSME Subsidies & Consumer Redressal Advisor",
        "name_hi": "एमएसएमई छूट व उपभोक्ता शिकायत सलाहकार",
        "category": "schemes",
        "category_label": "Regulatory & MSME",
        "icon": "CMD",
        "badge": "National Consumer Helpline",
        "scheme": "Citizen & Industry Service",
        "standards": ["BIS Act 2016", "Consumer Protection Act 2019"],
        "description": "Guiding small businesses on 50% MSME fee subsidies, women entrepreneur concessions, and citizens on BIS Care complaint lodging.",
        "description_hi": "छोटे उद्योगों को 50% सरकारी फीस छूट, महिला उद्यमियों को रियायतें और बीआईएस केयर शिकायत निवारण में विशेषज्ञ।",
        "key_tests": "Udyam Registration Verification, Licensing Fee Concessions, 6-digit HUID Authenticity, Enforcement Penalties",
        "default_question": "What financial subsidies and fee concessions are available for MSMEs and startups applying for BIS certification?",
        "system_role": "You are the Principal Regulatory and MSME Facilitation Officer at the Bureau of Indian Standards. Explain the BIS Act 2016 enforcement provisions, 50% annual marking fee concessions for micro enterprises, 20% concessions for small enterprises, and how consumers can use the BIS Care App."
    }
]

CATEGORIES_MAP = [
    {"id": "all", "label": "All Categories (16)", "label_hi": "सभी श्रेणियां (16)"},
    {"id": "safety", "label": "Safety & PPE (4)", "label_hi": "सुरक्षा व पीपीई (4)"},
    {"id": "electronics", "label": "Electronics & IT (2)", "label_hi": "इलेक्ट्रॉनिक्स व आईटी (2)"},
    {"id": "industrial", "label": "Heavy & Construction (3)", "label_hi": "भारी उद्योग व निर्माण (3)"},
    {"id": "hallmarking", "label": "Precious Metals (2)", "label_hi": "हॉलमार्किंग व आभूषण (2)"},
    {"id": "consumer", "label": "Consumer & Home (3)", "label_hi": "घरेलू व उपभोक्ता (3)"},
    {"id": "food", "label": "Food & Water (1)", "label_hi": "खाद्य व पेयजल (1)"},
    {"id": "schemes", "label": "Regulatory & MSME (1)", "label_hi": "योजनाएं व एमएसएमई (1)"}
]


def get_agent_by_id(agent_id: str):
    if not agent_id:
        return None
    for a in AGENTS_CATALOG:
        if a["id"] == agent_id:
            return a
    return None
